### PR TITLE
fix: install pytorch cu116 for server docker image

### PR DESCRIPTION
**Pull request by ZiniuYu**
This PR fixes the error in linked issue

### CODE REVIEW

**Review by jemmyshin — APPROVED** [review]

**Comment by jemmyshin** [comment]
please rebuild the image and reply to the communities.

**Comment by numb3r3** [comment]
@ZiniuYu Does the hub executor also suffer from this issue?

**Comment by ZiniuYu** [comment]
> @ZiniuYu Does the hub executor also suffer from this issue?

I just tested both Torch and ONNX executors, they are all fine

**Comment by numb3r3** [comment]
> I just tested both Torch and ONNX executors, they are all fine

Then, I doubled if this issue comes from cuda? And I would not recommend pinning the cuda version. Our work should work on all stable cuda versions.

**Comment by numb3r3** [comment]
So, please try to make it work with `cuda-11.6.0`, rather than freeze the cuda version.

**Review by numb3r3 — APPROVED** [review]
LGTM

**Pull request merged**
